name: Flutter Unit Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'   # <-- set your Flutter version
          channel: stable

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run only your unit tests
      - name: Run unit tests
        run: flutter test test/unit_test.dart
